# Generated by Django 5.1.2 on 2024-11-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpage",
            name="button_text_two",
            field=models.TextField(blank=True, default="Add to Calender", null=True),
        ),
    ]
