# Generated by Django 5.1.2 on 2024-11-13 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emergency", "0001_initial"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emergencypage",
            options={
                "verbose_name": "Emergency service Page",
                "verbose_name_plural": "Emergency service Pages",
            },
        ),
        migrations.AddField(
            model_name="emergencypagecontent",
            name="icon_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
