version: '3.8'

services:
  wagtail_app:
    build: .
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
