  version: '3.8'

  services:
    wagtail_app:
      build: .
      ports:
        - "8003:8003"
      command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8003"
      volumes:
        - .:/app
      env_file:
          - .env

      environment:
          - PYTHONPATH=/app
          - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
          - DB_NAME=${DB_NAME}
          - DB_USER=${DB_USER}
          - DB_PASSWORD=${DB_PASSWORD}
          - DB_HOST=${DB_HOST}
          - DB_PORT=${DB_PORT}
      depends_on:
          - hormony_db

    hormony_db:
      image: postgres:17
      restart: always
      environment:
        - "POSTGRES_HOST_AUTH_METHOD=trust"
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
    
      volumes:
        # - postgres_data:/var/lib/postgresql/data
        - /home/jarvis/projects/wagtail_Harmony/mydb:/var/lib/postgresql/data
      
      ports:
        - "5433:5433"
      env_file:
        - .env
      expose:
        - 5433

  volumes:
    postgres_data: {}
