# Generated by Django 5.1.2 on 2024-11-27 11:38

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hamburger",
                    wagtail.fields.StreamField(
                        [("element", 5)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {}),
                            2: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 1), ("page", 2)]],
                                {},
                            ),
                            4: (
                                "wagtail.blocks.StreamBlock",
                                [[("navpages", 3)]],
                                {"required": False},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("icon_image", 0), ("category", 1), ("children", 4)]],
                                {},
                            ),
                        },
                        null=True,
                    ),
                ),
                (
                    "footer",
                    wagtail.fields.StreamField(
                        [("element", 4)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("page", 1)]],
                                {},
                            ),
                            3: (
                                "wagtail.blocks.StreamBlock",
                                [[("navpages", 2)]],
                                {"required": False},
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("section_name", 0), ("children", 3)]],
                                {},
                            ),
                        },
                        null=True,
                    ),
                ),
                (
                    "social_link",
                    wagtail.fields.StreamField(
                        [("element", 2)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "URL", "required": False},
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("icon", 0), ("url", 1)]],
                                {},
                            ),
                        },
                        null=True,
                    ),
                ),
                (
                    "office_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "favicon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "footer_logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "footer_logo_page_link",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "footer_seal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "header_logo_page_link",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Navigation",
                "verbose_name_plural": "Navigation",
            },
        ),
    ]
