# Generated by Django 5.1.2 on 2024-11-13 11:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hamburger",
                    wagtail.fields.StreamField(
                        [("element", 3), ("dropdown", 5)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            2: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "URL", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("page", 1), ("url", 2)]],
                                {},
                            ),
                            4: (
                                "wagtail.blocks.StreamBlock",
                                [[("element", 3)]],
                                {"default": []},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("children", 4)]],
                                {},
                            ),
                        },
                        null=True,
                    ),
                ),
                (
                    "footer",
                    wagtail.fields.StreamField(
                        [("element", 3)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            2: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "URL", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("page", 1), ("url", 2)]],
                                {},
                            ),
                        },
                        null=True,
                    ),
                ),
                (
                    "footer_logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Navigation",
                "verbose_name_plural": "Navigation",
            },
        ),
    ]
