# Generated by Django 5.1.2 on 2024-11-13 11:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conf", "0002_navigationsettings_favicon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigationsettings",
            name="footer",
            field=wagtail.fields.StreamField(
                [("element", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "URL", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("category", 0), ("title", 0), ("page", 1), ("url", 2)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="navigationsettings",
            name="hamburger",
            field=wagtail.fields.StreamField(
                [("element", 3), ("dropdown", 5)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "URL", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("category", 0), ("title", 0), ("page", 1), ("url", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.StreamBlock",
                        [[("element", 3)]],
                        {"default": []},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("children", 4)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
