# Generated by Django 5.1.2 on 2024-11-13 12:05

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conf", "0005_alter_navigationsettings_footer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigationsettings",
            name="footer",
            field=wagtail.fields.StreamField(
                [("element", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("page", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.StreamBlock",
                        [[("navpages", 3)]],
                        {"required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("icon_image", 0), ("category", 1), ("children", 4)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="navigationsettings",
            name="hamburger",
            field=wagtail.fields.StreamField(
                [("element", 5), ("dropdown", 7)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("page", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.StreamBlock",
                        [[("navpages", 3)]],
                        {"required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("icon_image", 0), ("category", 1), ("children", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.StreamBlock",
                        [[("element", 5)]],
                        {"required": False},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("children", 6)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
