# Generated by Django 5.1.2 on 2024-11-14 03:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conf", "0007_alter_navigationsettings_footer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigationsettings",
            name="footer",
            field=wagtail.fields.StreamField(
                [("element", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("page", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.StreamBlock",
                        [[("navpages", 2)]],
                        {"required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("section_name", 0),
                                ("office_address", 0),
                                ("phone_number", 0),
                                ("children", 3),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
