# Generated by Django 5.1.2 on 2024-11-14 03:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conf", "0010_navigationsettings_office_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="navigationsettings",
            name="social_link",
            field=wagtail.fields.StreamField(
                [("element", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    1: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "URL", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("icon_image", 0), ("url", 1)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
