# Generated by Django 5.1.2 on 2024-11-14 03:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conf", "0011_navigationsettings_social_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigationsettings",
            name="social_link",
            field=wagtail.fields.StreamField(
                [("element", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "URL", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("icon_image", 0), ("icon", 1), ("url", 2)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
