# Generated by Django 5.1.2 on 2024-11-28 04:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interest", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="singlepagefeatureddetailpageimages",
            name="page",
        ),
        migrations.RemoveField(
            model_name="singlepagefeatureddetailpageimages",
            name="image",
        ),
        migrations.DeleteModel(
            name="SinglePageFeaturedDetail",
        ),
        migrations.DeleteModel(
            name="SinglePageFeaturedDetailPageImages",
        ),
    ]
