# Generated by Django 5.1.2 on 2024-11-26 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interest", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pointsofinterest",
            name="category",
        ),
        migrations.RemoveField(
            model_name="singlepointsofinterest",
            name="category",
        ),
    ]
