# Generated by Django 5.1.2 on 2024-11-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "interest",
            "0002_rename_bottom_link_page_pointsofinterest_footer_link_page_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="singlepointsofinterest",
            name="single_land_image",
        ),
        migrations.AlterField(
            model_name="pointsofinterest",
            name="footer_heading",
            field=models.TextField(
                blank=True,
                default="Submit your fun photo at any point of interested",
                null=True,
            ),
        ),
    ]
