# Generated by Django 5.1.2 on 2024-11-27 04:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="electionspage",
            name="button_text_one",
        ),
        migrations.RemoveField(
            model_name="electionspage",
            name="button_text_three",
        ),
        migrations.RemoveField(
            model_name="electionspage",
            name="button_text_two",
        ),
        migrations.RemoveField(
            model_name="electionspage",
            name="heading_one",
        ),
        migrations.RemoveField(
            model_name="electionspage",
            name="heading_two",
        ),
        migrations.RemoveField(
            model_name="electionspage",
            name="link_page_one",
        ),
        migrations.RemoveField(
            model_name="electionspage",
            name="link_page_three",
        ),
        migrations.RemoveField(
            model_name="electionspage",
            name="link_page_two",
        ),
        migrations.RemoveField(
            model_name="electionspage",
            name="nomination_heading",
        ),
        migrations.RemoveField(
            model_name="electionspage",
            name="sub_heading_one",
        ),
        migrations.RemoveField(
            model_name="electionspage",
            name="sub_heading_two",
        ),
    ]
