# Generated by Django 5.1.2 on 2024-11-13 03:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="electionspage",
            options={
                "verbose_name": "Elections Page",
                "verbose_name_plural": "Elections Pages",
            },
        ),
    ]
