# Generated by Django 5.1.2 on 2024-11-27 09:25

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0002_remove_businesspage_growth_data_number_one_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Growth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("text", models.CharField(blank=True, max_length=200, null=True)),
                ("number", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buginess_growth",
                        to="business.businesspage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
