# Generated by Django 5.1.2 on 2024-11-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0003_growth"),
    ]

    operations = [
        migrations.AddField(
            model_name="growth",
            name="unit",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
