# Generated by Django 5.1.2 on 2024-11-27 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0005_businesspage_feature_heading_landfreatures"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesspage",
            name="feature_button_text",
            field=models.TextField(blank=True, default="Share Story", null=True),
        ),
        migrations.AddField(
            model_name="businesspage",
            name="feature_link_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
    ]
