# Generated by Django 5.1.2 on 2024-11-27 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0007_singlelandfeature_landproperties_and_more"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SinglePageFeaturedDetailPageImages",
            new_name="LandImages",
        ),
    ]
