# Generated by Django 5.1.2 on 2024-11-27 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0008_rename_singlepagefeatureddetailpageimages_landimages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="singlelandfeature",
            name="land_image",
        ),
    ]
