# Generated by Django 5.1.2 on 2024-11-27 10:30

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0009_remove_singlelandfeature_land_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landimages",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_land_images",
                to="business.singlelandfeature",
            ),
        ),
    ]
