# Generated by Django 5.1.2 on 2024-11-13 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meetingspage",
            name="bottom_link_page",
        ),
    ]
