# Generated by Django 5.1.2 on 2024-11-25 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0002_meetingtypes_remove_meetingpage_meeting_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meetingspage",
            name="meeting_type",
        ),
    ]
