# Generated by Django 5.1.2 on 2024-11-25 06:22

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0001_initial"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historiespage",
            name="bottom_button_text",
        ),
        migrations.RemoveField(
            model_name="historiespage",
            name="bottom_heading",
        ),
        migrations.RemoveField(
            model_name="historiespage",
            name="bottom_image_one",
        ),
        migrations.RemoveField(
            model_name="historiespage",
            name="bottom_image_two",
        ),
        migrations.RemoveField(
            model_name="historiespage",
            name="bottom_link_page",
        ),
        migrations.RemoveField(
            model_name="historiespage",
            name="heading",
        ),
        migrations.RemoveField(
            model_name="historiespage",
            name="search",
        ),
        migrations.RemoveField(
            model_name="historiespage",
            name="short_description",
        ),
        migrations.RemoveField(
            model_name="historiespage",
            name="short_heading",
        ),
        migrations.CreateModel(
            name="HistoryDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("history_year", models.CharField(max_length=200, null=True)),
                (
                    "heading",
                    models.TextField(
                        blank=True, default="History of Harmony", null=True
                    ),
                ),
                ("short_heading", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_page_details",
                        to="history.historiespage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoryContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("content_short_description", models.TextField(blank=True, null=True)),
                ("content_full_description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_contents",
                        to="history.historydetails",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="HistoryPage",
        ),
    ]
