# Generated by Django 5.1.2 on 2024-11-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0003_historiespage_bottom_button_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historydetails",
            name="heading",
        ),
        migrations.AddField(
            model_name="historiespage",
            name="heading",
            field=models.TextField(blank=True, default="History of Harmony", null=True),
        ),
    ]
