# Generated by Django 5.1.2 on 2024-11-13 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("permits", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permitspage",
            options={
                "verbose_name": "Business Permits",
                "verbose_name_plural": "Businesses Permits",
            },
        ),
    ]
