# Generated by Django 5.1.2 on 2024-11-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsdetailpage",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
