# Generated by Django 5.1.2 on 2024-11-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_homepage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="quick_links_text",
            field=models.TextField(blank=True, default="Quick Links", null=True),
        ),
    ]
