name: Harmony VM Deployment

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: pull latest code
      run: |
          echo "Take the pull "
          git pull origin main || { echo "Git pull failed"; exit 1; }

    - name: Set environment variables from GitHub Secrets
        run: |
          export DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
          export DB_NAME=${{ secrets.DB_NAME }}
          export DB_USER=${{ secrets.DB_USER }}
          export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          export DB_HOST=${{ secrets.DB_HOST }}
          export DB_PORT=${{ secrets.DB_PORT }}
        run: echo "Environment variables set successfully"

    - name : run docker
      run: |
        echo "Docker build"
        docker compose build --no-cache|| { echo "docker failed"; exit 2; }

        echo "Docker run in background"
        docker compose up -d|| { echo "docker failed background"; exit 3; }
        

      


