name: Harmony VM Deployment

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  
      - name: Set environment variables from GitHub Secrets
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }} >> .env
          DB_NAME: ${{ secrets.DB_NAME }} >> .env
          DB_USER: ${{ secrets.DB_USER }} >> .env
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }} >> .env
          DB_HOST: ${{ secrets.DB_HOST }}  >> .env
          DB_PORT: ${{ secrets.DB_PORT }} >> .env
        run: echo "Environment variables set successfully"



      - name: Pull latest code
        run: git pull origin main || { echo "Git pull failed"; exit 1; }



      - name: Run Docker
        run: |
          echo "Docker build"
          docker compose build --no-cache || { echo "docker failed"; exit 2; }

          echo "Docker run in background"
          docker compose up -d || { echo "docker failed background"; exit 3; }
